### ISSUE TITLE
[GC] Update needed for the GC-MS documentation

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPSDocumentation#107]
The documentation was updated and will be available on the documentation website.
https://github.com/CCMS-UCSD/GNPSDocumentation/pull/106

It needs the following:
- Removing the steps from the page, and create more space between steps (avoid paragraph).
- Careful update of parameter description. 
- Providing informations (basic guidelines and links) on MZmine and direct submission module. https://github.com/CCMS-UCSD/GNPS_Workflows/issues/232
- Providing informations (basic guidelines and links) on MS-DIAL processing.

Note that the GC library/network workflow parameters will be slightly modified soon, so changes will have to account for that. https://github.com/CCMS-UCSD/GNPS_Workflows/issues/235

@MelissaESPOSITO @mabelgon88 @aaksenov1

**Comment by lfnothias** [comment]
The address for the GC-MS documentation is https://ccms-ucsd.github.io/GNPSDocumentation/gc-ms-documentation.md

**Comment by mwang87** [comment]
Merged and fixed bugs in documentation. Deployed, @lfnothias  will check.
