### ISSUE TITLE
[ili] Reorganization of ili for classical molecular networking

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#118]
Reorganization of running ili with GNPS to refactor out of the metadata section, which metadata specific portions remaining in place.

**Comment by mwang87** [comment]
Here is a working example: https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=04b29a1fddee4516984ae590ee19cb7b&view=view_ili

**Comment by abauermeister** [comment]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=22394b527c6d4cd1b391d76176d3c4d7

**Comment by mwang87** [comment]
It seems that the precuror intensity for MS2 spectra is missing on some instruments. We can revise the code to go back to spectral counts rather than sum precursor intensity.

**Comment by mwang87** [comment]
Testing here: 

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=a3ca7eee878e4559869132b264209e01

@abauermeister please confirm it is fixed when job is finished.

**Comment by abauermeister** [comment]
Yes, it is fixed. Thanks Ming!
