### ISSUE TITLE
[IIN] Documentation for IIN

### ISSUE THREAD

**Issue by robinschmid** [CCMS-UCSD/GNPSDocumentation#125]
Hey where should we put the documentation on IIN?

It is related to FBMN. Maybe we have a standalone IIN documentation for all the different tools?
- mzmine
- xcms (camera)
- ms-dial

@XsirdanielX @mwang87 @lfnothias @MelissaESPOSITO

**Comment by lfnothias** [comment]
I think that requires a separate documentation. Lets work on this during the month of December.

**Comment by robinschmid** [comment]
Ok

**Comment by mwang87** [comment]
I think it could possibly be a separate section in the GNPS documentation but it'll be quite large. 

If we organize it properly within GNPS it would be OK like it is done with FBMN, but open to having it be separate documetnation and a separate markdown website.

**Comment by XsirdanielX** [comment]
I'd suggest a separate section under advanced workflows, or we could add additional taps for FBMN.
I also just talked the Annelize and another visitor who would be able to help out with writing this down. Maybe we can make team for the different tools?

**Comment by robinschmid** [comment]
Maybe you are right FBMN is already complex enough and we should separate IIN and link out to the FBMN documentation.
We could have the same structure then:
- Ion identity-FBMN
    - MZmine (@robinschmid )
    - XCMS (@lfnothias  @jorainer )
    - MS-DIAL (@lfnothias )

**Comment by mwang87** [comment]
I think that’s perfect! Let me make place holder files in a branch and once finished we can add it to master and it’ll auto go live

**Comment by mwang87** [comment]
Created this branch to organize documentation for it:

https://github.com/CCMS-UCSD/GNPSDocumentation/pull/140

**Comment by mwang87** [comment]
Preliminary version of documentation is going live now.

**Comment by mwang87** [comment]
merged and deployed. closing
