### ISSUE TITLE
[Qemistree] Documentation

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#142]
1. Find place to put it in the docs
1. Write docs
1. Create examples

**Comment by mwang87** [comment]
Add to this branch: https://github.com/CCMS-UCSD/GNPSDocumentation/tree/qemistree

**Comment by mwang87** [comment]
@anupriyatripathi how is the documentation going?

**Comment by anupriyatripathi** [comment]
> @anupriyatripathi how is the documentation going?
We are going to differ this issue to 2020 January. We need to update GNPS Qemistree and provide documentation accordingly. Let's regroup after the break.

**Comment by mwang87** [comment]
@anupriyatripathi could you add some quick notes on it. Simply saying how you get the input data is already very instructive.
