### ISSUE TITLE
the origin of nodes in tne network

### ISSUE THREAD

**Issue by 10212004** [CCMS-UCSD/GNPSDocumentation#274]
I am very grateful to contact you about my question.
My work is to identify the compounds in Chinese patent medicine. So i want to know the origin of  nodes through molecular networking. Make the graph into a pie chart, i can get the origin of nodes and the proportion of groups in the nodes. There are 9 groups in my metadata. For example  A-I .But the origin of all nodes were 3 groups in the finished network. The 3 groups were A、B、H.   None of nodes in network originated from other 6 groups. why?  In normal situation , the origins of some nodes should be one or two of these 6 groups. 
When I repeat the same operation to make molecular networking, all modes only originated from only one group,  Why the results were different. I don not understand. 
I will wait for your reply.

**Comment by mwang87** [comment]
You might try asking this question at GNPS office hours https://ccms-ucsd.github.io/GNPSDocumentation/contact/ or on the forum:  https://groups.google.com/forum/#!forum/molecular_networking_bug_reports
