### ISSUE TITLE
How to find retention time of a particular node in classical molecular network

### ISSUE THREAD

**Issue by saghadejia** [CCMS-UCSD/GNPSDocumentation#275]
I m using MN to identify new compound from my plant extract, but it is difficult for me to find the exact retention of a particular node from my generated network in spectral data (TIC viewed using xcalibur). 
Please I need help on how to find the exact retention of a particular network  using classical MN workflow

**Comment by mwang87** [comment]
You can find it in two places:

![image](https://user-images.githubusercontent.com/96528/90543670-e5530f00-e13a-11ea-9859-f7bd0052804b.png)

and if you want it per file:

![image](https://user-images.githubusercontent.com/96528/90543706-eedc7700-e13a-11ea-8659-9555f167a4a9.png)

Stop by office hours if you need more help!
