### ISSUE TITLE
Update Batch Documentation to Mention Morgan as Facilitator

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#36]

**Comment by mwang87** [comment]
@klj0019 Are any updates ready to be reviewed?

**Comment by klj0019** [comment]
Still wasn't quite sure of what you wanted. Sorry I forgot about this one.

**Comment by mwang87** [comment]
The required steps for library creation should be as follows:

1. Create batch file according to the metadata format
2. Upload mzXML/mzML files to GNPS
3. Give batch and mzXML files to Morgan
4. Morgan will create private spectral library
5. Reviewed by contributor
6. Made public

Can you put that and reword the text into the documentation in the correct location and relevant links. 

Thanks!

**Comment by mwang87** [comment]
Merged.
