### ISSUE TITLE
How to delete dataset

### ISSUE THREAD

**Issue by SamuelPlane** [CCMS-UCSD/GNPSDocumentation#360]
I'm currently unsure of how to delete a dataset if that is at all possible. If it is could that be added to the documentation please?

I am trying to delete a dataset as I am testing out this service on behalf of my organisation, and as such I have simply provided test data rather than any data with scientific relevance. 

Many thanks

**Comment by mwang87** [comment]
Its not possible for you to delete a public dataset. For more info on MassIVE, would recommend documentation. Admins can delete for you.
