### ISSUE TITLE
GNPS-MassIVE Datasets issue-positive and negative merge mode raw data

### ISSUE THREAD

**Issue by diaorao** [CCMS-UCSD/GNPSDocumentation#394]
Hi,
I'm a bit worried about my MS data which is in positive and negative merge mode. Is that necessary to export the negative mode and positive mode files from LC-MS individually for uploading to MassIVE datasets? (I saw the video guide say it needs rawdata, but mine is in merge mode )
I didn't try it yet and I didn't find a guide for this issue. Now I'm converting these raw data files to MZML format by using MS convert, trying to make it into two mode files. positive and negative. And I don't know if it works, would anyone help me out this issue I will be grateful, thank you!

**Comment by mwang87** [comment]
Keeping them merged should be no problem.
