### ISSUE TITLE
Add Uptime Indicator to GNPS Documentation

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#44]
https://stats.uptimerobot.com/Am4PLUWn3

**Comment by mwang87** [comment]
Assigned to Mauricio

**Comment by lfnothias** [comment]
Nice. I made an iframe version. See #53

**Comment by mwang87** [comment]
https://github.com/CCMS-UCSD/GNPSDocumentation/pull/59
