### ISSUE TITLE
Update GNPS Super-Quickstart Documentation

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#45]
1. Screenshots for Classical and FBMN
2. Docs and screenshots for Conversion
3. Docs for Dataset Creation

**Comment by jgauglitz** [comment]
I can address this task. #45.

**Comment by mwang87** [comment]
Any updates on this issue?

**Comment by mwang87** [comment]
Are there updates on this issue?

**Comment by mwang87** [comment]
How is this task going?
