### ISSUE TITLE
Validate Step by Step for mzmine2 processing and fix issues

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#46]

**Comment by allegra-aron** [comment]
Hi Ming, I can help with this issue.

**Comment by mwang87** [comment]
Thanks allegra, assigned to you!

**Comment by mwang87** [comment]
Here is the documentation live:

https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking-with-mzmine2/

and the git source:

https://github.com/CCMS-UCSD/GNPSDocumentation/blob/master/docs/featurebasedmolecularnetworking-with-mzmine2.md

Ming

**Comment by mwang87** [comment]
Any updates on this issue?

**Comment by lfnothias** [comment]
I review that page few days ago, and it looks fine. 
It would be nice to add couple of updated batch files (with the version).

**Comment by grimcynthia** [comment]
I'm currently working through the documentation with MZmine 2.51 and noticing a few menus have moved compared to the version it was written for, also there's no description for ADAP chromatogram builder, would this be a part of this issue?

**Comment by mwang87** [comment]
Thanks @grimcynthia If you could offer fixes for an updated version of MZmine2.51 we'd very much welcome it. 

The current guide was developed for v2.33 which we would recommend you use with our documentation.

**Comment by grimcynthia** [comment]
@mwang87 I'm also having trouble with my GNPS output for my own data so I'm looking to work through the example data and get that working to help me troubleshoot.

Is there a way to also help the documentation while I'm doing this? Like make a note of if it works with 2.51?

**Comment by mwang87** [comment]
Yes, definitely, we have some tutorial guides here for the output of MZMine2:

https://ccms-ucsd.github.io/GNPSDocumentation/tutorials/americangutmzmine/

and also for the actual documentation for GNPS for FBMN:

https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking/

Any errors or improvements would be super welcome!

Definitely let us know if you have questions too.

**Comment by mwang87** [comment]
Closing as this has been addressed by @grimcynthia
