### ISSUE TITLE
Updates for Troubleshooting for FBMN

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#57]
https://ccms-ucsd.github.io/GNPSDocumentation/troubleshooting/

**Comment by mwang87** [comment]
Could you please provide an ETA for this issue?

**Comment by mccall-lab-OU** [comment]
Hi Ming,

I was planning on accumulating problems as I teach new students over the
semester, and then doing an overall write-up around December. I can also
progressively add issues, if that's easier for you.

Laura-Isobel

**Comment by mwang87** [comment]
No problem! Lets go ahead and do it from that perspective, I think thats great.

Ming

**Comment by mwang87** [comment]
Addressed and merged here: 

https://github.com/CCMS-UCSD/GNPSDocumentation/pull/144
