### ISSUE TITLE
Update GNPS Metadata fileformat to recommend ReDU file format to build off of

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#61]

**Comment by mwang87** [comment]
could @alan-jarmusch handle this documentation?

**Comment by alan-jarmusch** [comment]
@mwang87 the place I see metadata description is here
https://ccms-ucsd.github.io/GNPSDocumentation/networking/
there are a few links in the FBMN section to that same section.
Would it make sense to have a dedicated page in the data preparation/upload section?

**Comment by mwang87** [comment]
Yes, lets have a section under Recommended Data Analysis that is dedicated to metadata. This can be referenced from all locations that need metadata. We will also have an addendum in the particular networking section to note additional columns for ili mapping but those can remain where they are since that feature is not supported by other tools.

**Comment by alan-jarmusch** [comment]
will do. thx

**Comment by alan-jarmusch** [comment]
@mwang87 pull request submitted
