### ISSUE TITLE
Update documentation to make note that minimum matched peaks is exclusive

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPSDocumentation#70]
that is, if you set 4, you need at least 5 peak matches to be considered.

Additionally, we should add that the absolute minimum number of peaks for networking is 5 in a spectrum or else it will be thrown out.

**Comment by madeleineernst** [comment]
added a note that the absolute minimum number of peaks for networking is 5 and created a PR #71

**Comment by mwang87** [comment]
Confirmed and merged.
