### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by chasemc** [CCMS-UCSD/GNPSDocumentation#89]
![image](https://user-images.githubusercontent.com/18691127/65391411-86b8c180-dd2e-11e9-86e0-3e51b2b8e1b1.png)

At bottom of: https://ccms-ucsd.github.io/GNPSDocumentation/resultviews/

**Comment by chasemc** [comment]
https://ccms-ucsd.github.io/GNPSDocumentation/tutorials/bacterianetworking/

https://ccms-ucsd.github.io/GNPSDocumentation/tutorials/americangut-ms-dial/

**Comment by mwang87** [comment]
Thanks @chasemc! Fixed and deployed!
